spring:
  application:
    name: file-service
  datasource:
    url: jdbc:mysql://154.83.16.100:3306/taobao-01?serverTimezone=GMT%2B8&guseUnicode=true&characterEncoding=utf-8
    #url jdbc:mysql://192.168.:3306/a-song?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: taobao-01
    password: wX8dncDfWzdsPr4f
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    #指定数据库
    database: mysql
    #打印sql
    show-sql: true
    hibernate:
      #开启数据库更新表
      ddl-auto: update
      #指定命名策略
      naming:
        implicit-strategy: org.hibernate.boot.model.naming.ImplicitNamingStrategyComponentPathImpl
    properties:
      hibernate:
        #Hibernate方言
        dialect: org.hibernate.dialect.MySQL5Dialect
server:
  port: 80